organization:
  name: default

clusters:
  - id: my-kafka-cluster
    name: My Kafka Cluster
    bootstrapServers: "my-bootstrap-server:9092"
    properties: |
      security.protocol=SASL_SSL
      sasl.mechanism=PLAIN
      sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='username' password='password';
    schemaRegistry:
      id: my-schema-registry
      url: "http://my-schema-registry:8081"
      security:
        username: "username"
        password: "password"

auth:
  demo-users:
    - email: admin@conduktor.io
      password: admin